# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Neftali\Documents\GitHub\CMS\CMS.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(710, 500)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 681, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.Attendance = QtWidgets.QWidget()
        self.Attendance.setObjectName("Attendance")
        self.tableWidget = QtWidgets.QTableWidget(self.Attendance)
        self.tableWidget.setGeometry(QtCore.QRect(20, 40, 631, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tabWidget.addTab(self.Attendance, "")
        self.Roster = QtWidgets.QWidget()
        self.Roster.setObjectName("Roster")
        self.tableView = QtWidgets.QTableView(self.Roster)
        self.tableView.setGeometry(QtCore.QRect(30, 20, 301, 381))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.Roster)
        self.pushButton.setGeometry(QtCore.QRect(380, 130, 121, 51))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.Roster, "")
        self.Projects = QtWidgets.QWidget()
        self.Projects.setObjectName("Projects")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Projects)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 70, 321, 301))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.textEdit = QtWidgets.QTextEdit(self.Projects)
        self.textEdit.setGeometry(QtCore.QRect(370, 140, 241, 131))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(self.Projects)
        self.comboBox.setGeometry(QtCore.QRect(500, 110, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.Projects)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 300, 101, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label = QtWidgets.QLabel(self.Projects)
        self.label.setGeometry(QtCore.QRect(380, 110, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Projects)
        self.label_2.setGeometry(QtCore.QRect(370, 300, 121, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton1 = QtWidgets.QPushButton(self.Projects)
        self.pushButton1.setGeometry(QtCore.QRect(540, 330, 75, 23))
        self.pushButton1.setObjectName("pushButton1")
        self.groupBox = QtWidgets.QGroupBox(self.Projects)
        self.groupBox.setGeometry(QtCore.QRect(350, 80, 291, 291))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.raise_()
        self.tabWidget_2.raise_()
        self.textEdit.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.tabWidget.addTab(self.Projects, "")
        self.Export = QtWidgets.QWidget()
        self.Export.setObjectName("Export")
        self.exportbutton = QtWidgets.QPushButton(self.Export)
        self.exportbutton.setGeometry(QtCore.QRect(130, 100, 131, 51))
        self.exportbutton.setObjectName("exportbutton")
        self.tabWidget.addTab(self.Export, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Student1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Student2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Units"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Today"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Date2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Total Unexcused"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "HW1"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "HW2"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Total Grade"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Attendance), _translate("Form", "Attendance"))
        self.pushButton.setText(_translate("Form", "Import From Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roster), _translate("Form", "Roster"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form", "Project 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form", "Project 2"))
        self.label.setText(_translate("Form", "Choose Project"))
        self.label_2.setText(_translate("Form", "Choose Weekly Points"))
        self.pushButton1.setText(_translate("Form", "Submit"))
        self.groupBox.setTitle(_translate("Form", "Give Feedback"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Projects), _translate("Form", "Projects"))
        self.exportbutton.setText(_translate("Form", "Export As Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Export), _translate("Form", "Export"))

