# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Neftali\Documents\GitHub\CMS\CMS1.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 561))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Attendance = QtWidgets.QWidget()
        self.Attendance.setObjectName("Attendance")
        self.attendanceTable = QtWidgets.QTableWidget(self.Attendance)
        self.attendanceTable.setGeometry(QtCore.QRect(10, 10, 481, 511))
        self.attendanceTable.setObjectName("attendanceTable")
        self.attendanceTable.setColumnCount(0)
        self.attendanceTable.setRowCount(0)
        self.addDateButton = QtWidgets.QPushButton(self.Attendance)
        self.addDateButton.setGeometry(QtCore.QRect(520, 30, 131, 31))
        self.addDateButton.setObjectName("addDateButton")
        self.tabWidget.addTab(self.Attendance, "")
        self.Grades = QtWidgets.QWidget()
        self.Grades.setObjectName("Grades")
        self.gradesTable = QtWidgets.QTableWidget(self.Grades)
        self.gradesTable.setGeometry(QtCore.QRect(10, 10, 481, 511))
        self.gradesTable.setObjectName("gradesTable")
        self.gradesTable.setColumnCount(0)
        self.gradesTable.setRowCount(0)
        self.add_assignment = QtWidgets.QPushButton(self.Grades)
        self.add_assignment.setGeometry(QtCore.QRect(520, 30, 131, 31))
        self.add_assignment.setObjectName("add_assignment")
        self.tabWidget.addTab(self.Grades, "")
        self.Roster = QtWidgets.QWidget()
        self.Roster.setObjectName("Roster")
        self.pushButton = QtWidgets.QPushButton(self.Roster)
        self.pushButton.setGeometry(QtCore.QRect(520, 30, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.rosterView = QtWidgets.QTableView(self.Roster)
        self.rosterView.setGeometry(QtCore.QRect(10, 10, 481, 511))
        self.rosterView.setObjectName("rosterView")
        self.tabWidget.addTab(self.Roster, "")
        self.Projects = QtWidgets.QWidget()
        self.Projects.setObjectName("Projects")
        self.projectScrollBox = QtWidgets.QScrollArea(self.Projects)
        self.projectScrollBox.setGeometry(QtCore.QRect(20, 20, 281, 381))
        self.projectScrollBox.setMaximumSize(QtCore.QSize(281, 16777215))
        self.projectScrollBox.setWidgetResizable(False)
        self.projectScrollBox.setObjectName("projectScrollBox")
        self.projectPagesContent = QtWidgets.QWidget()
        self.projectPagesContent.setGeometry(QtCore.QRect(0, 0, 279, 369))
        self.projectPagesContent.setObjectName("projectPagesContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.projectPagesContent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.projectPagesContent)
        self.toolBox.setObjectName("toolBox")
        self.projectPage = QtWidgets.QWidget()
        self.projectPage.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.projectPage.setObjectName("projectPage")
        self.studentInProject = QtWidgets.QTableView(self.projectPage)
        self.studentInProject.setGeometry(QtCore.QRect(0, 0, 261, 141))
        self.studentInProject.setObjectName("studentInProject")
        self.projectFeedback = QtWidgets.QTableView(self.projectPage)
        self.projectFeedback.setGeometry(QtCore.QRect(0, 150, 261, 151))
        self.projectFeedback.setObjectName("projectFeedback")
        self.toolBox.addItem(self.projectPage, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 261, 243))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.projectScrollBox.setWidget(self.projectPagesContent)
        self.giveFeedBack = QtWidgets.QGroupBox(self.Projects)
        self.giveFeedBack.setGeometry(QtCore.QRect(330, 110, 421, 281))
        self.giveFeedBack.setObjectName("giveFeedBack")
        self.textScroll = QtWidgets.QScrollArea(self.giveFeedBack)
        self.textScroll.setGeometry(QtCore.QRect(20, 50, 381, 151))
        self.textScroll.setWidgetResizable(True)
        self.textScroll.setObjectName("textScroll")
        self.projectFeedBackContents = QtWidgets.QWidget()
        self.projectFeedBackContents.setGeometry(QtCore.QRect(0, 0, 379, 149))
        self.projectFeedBackContents.setObjectName("projectFeedBackContents")
        self.feedBackText = QtWidgets.QPlainTextEdit(self.projectFeedBackContents)
        self.feedBackText.setGeometry(QtCore.QRect(0, 0, 381, 151))
        self.feedBackText.setObjectName("feedBackText")
        self.textScroll.setWidget(self.projectFeedBackContents)
        self.chooseProject = QtWidgets.QComboBox(self.giveFeedBack)
        self.chooseProject.setGeometry(QtCore.QRect(20, 20, 151, 22))
        self.chooseProject.setObjectName("chooseProject")
        self.chooseProject.addItem("")
        self.projectDateEdit = QtWidgets.QDateEdit(self.giveFeedBack)
        self.projectDateEdit.setGeometry(QtCore.QRect(180, 20, 110, 22))
        self.projectDateEdit.setObjectName("projectDateEdit")
        self.weeklyPoints = QtWidgets.QComboBox(self.giveFeedBack)
        self.weeklyPoints.setGeometry(QtCore.QRect(20, 210, 151, 22))
        self.weeklyPoints.setObjectName("weeklyPoints")
        self.weeklyPoints.addItem("")
        self.submitFeedback = QtWidgets.QPushButton(self.giveFeedBack)
        self.submitFeedback.setGeometry(QtCore.QRect(330, 250, 75, 23))
        self.submitFeedback.setObjectName("submitFeedback")
        self.addProjectBttn = QtWidgets.QPushButton(self.Projects)
        self.addProjectBttn.setGeometry(QtCore.QRect(350, 20, 131, 31))
        self.addProjectBttn.setObjectName("addProjectBttn")
        self.tabWidget.addTab(self.Projects, "")
        self.export = QtWidgets.QWidget()
        self.export.setObjectName("export")
        self.tabWidget.addTab(self.export, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.toolBox.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addDateButton.setText(_translate("MainWindow", "Add Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Attendance), _translate("MainWindow", "Attendance"))
        self.add_assignment.setText(_translate("MainWindow", "Add Assignment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Grades), _translate("MainWindow", "Grades"))
        self.pushButton.setText(_translate("MainWindow", "Import Roster"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roster), _translate("MainWindow", "Roster"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.projectPage), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Page"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Page"))
        self.giveFeedBack.setTitle(_translate("MainWindow", "Give Feedback"))
        self.chooseProject.setCurrentText(_translate("MainWindow", "Choose Project"))
        self.chooseProject.setItemText(0, _translate("MainWindow", "Choose Project"))
        self.weeklyPoints.setItemText(0, _translate("MainWindow", "Weekly Points"))
        self.submitFeedback.setText(_translate("MainWindow", "Submit"))
        self.addProjectBttn.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Projects), _translate("MainWindow", "Projects"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export), _translate("MainWindow", "Export"))

