# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Neftali\Documents\GitHub\CMS\CMS1.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 561))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Attendance = QtWidgets.QWidget()
        self.Attendance.setObjectName("Attendance")
        self.tableWidget = QtWidgets.QTableWidget(self.Attendance)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 571, 511))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.Attendance, "")
        self.Grades = QtWidgets.QWidget()
        self.Grades.setObjectName("Grades")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Grades)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 481, 511))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.add_assignment = QtWidgets.QPushButton(self.Grades)
        self.add_assignment.setGeometry(QtCore.QRect(560, 60, 131, 31))
        self.add_assignment.setObjectName("add_assignment")
        self.tabWidget.addTab(self.Grades, "")
        self.Roster = QtWidgets.QWidget()
        self.Roster.setObjectName("Roster")
        self.pushButton = QtWidgets.QPushButton(self.Roster)
        self.pushButton.setGeometry(QtCore.QRect(540, 40, 86, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(self.Roster)
        self.tableView.setGeometry(QtCore.QRect(40, 20, 311, 431))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.Roster, "")
        self.Projects = QtWidgets.QWidget()
        self.Projects.setObjectName("Projects")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Projects)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 20, 281, 381))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(281, 16777215))
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 279, 369))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page.setObjectName("page")
        self.columnView = QtWidgets.QColumnView(self.page)
        self.columnView.setGeometry(QtCore.QRect(10, 0, 91, 241))
        self.columnView.setObjectName("columnView")
        self.tableView_2 = QtWidgets.QTableView(self.page)
        self.tableView_2.setGeometry(QtCore.QRect(110, 0, 141, 241))
        self.tableView_2.setObjectName("tableView_2")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.groupBox = QtWidgets.QGroupBox(self.Projects)
        self.groupBox.setGeometry(QtCore.QRect(330, 20, 421, 281))
        self.groupBox.setObjectName("groupBox")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_3.setGeometry(QtCore.QRect(20, 50, 381, 151))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 379, 149))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 381, 151))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(180, 20, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 210, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 250, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.Projects, "")
        self.export = QtWidgets.QWidget()
        self.export.setObjectName("export")
        self.tabWidget.addTab(self.export, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Attendance), _translate("MainWindow", "Attendance"))
        self.add_assignment.setText(_translate("MainWindow", "Add Assignment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Grades), _translate("MainWindow", "Grades"))
        self.pushButton.setText(_translate("MainWindow", "Import Roster"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Roster), _translate("MainWindow", "Roster"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Page 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Page"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Give Feedback"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Choose Project"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose Project"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Weekly Points"))
        self.pushButton_2.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Projects), _translate("MainWindow", "Projects"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export), _translate("MainWindow", "Export"))

